name: Add friend link

on:
  issues:
    types: [opened]

jobs:
  check_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: node ./scripts/handle-issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}