name: Friend link workflow

on:
  issues:
    types: [ opened, edited, closed, deleted, reopened ]

jobs:
  check_issue:
    runs-on: ubuntu-latest
    concurrency:
      group: friend-link
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Run script
        run: python .github/scripts/add_friend_link.py ${{ github.event.issue.number }}
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          # 操作，opend, edited, reopened
          ACT_TYPE: ${{ github.event.action }}