
name: 部署页面

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8


      - name: setup Node.js
        run: |-
          pnpm install

      - name: build page
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > dist/.nojekyll

      - name: deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist